ci: remove shfmt

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -26,3 +26,13 @@ pre-commit:
               - '*.yaml'
               - '*.yml'
             stage_fixed: true
+          - run: |
+              if command -v shfmt >/dev/null 2>&1; then
+                shfmt -w -i=2 {staged_files}
+              else
+                echo "[ERROR] shfmt missing. Install it!" >&2
+                exit 1
+              fi
+            glob:
+              - '*.sh'
+            stage_fixed: true
